### ISSUE TITLE
npm test不能全部通过

### ISSUE THREAD

**Issue by roylhb** [syaning/zhihu-api#4]
41 passing (39s)
  3 failing

  1) api.question api.question.latest():

     SyntaxError: Unexpected token <
         at Object.parse (native)
         at lib/api/question.js:48:25
         at process._tickCallback (internal/process/next_tick.js:103:7)

  2) api.question api.question.list(start, offset):
   
      SyntaxError: Unexpected token <
          at Object.parse (native)
          at lib/api/question.js:48:25
          at process._tickCallback (internal/process/next_tick.js:103:7)

  3) api.user #user.questions(page):
    
     Error: connect ETIMEDOUT 220.194.224.15:443
         at Object.exports._errnoException (util.js:890:11)
         at exports._exceptionWithHostPort (util.js:913:20)
         at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1059:14)

**Comment by syaning** [comment]
因为知乎改版，有些页面现在已经访问不到。我会尽快对现有API进行重新测试和调整。
